name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
          DB_NAME: test
          DB_USER: test
          DB_PASSWORD: test
          DB_HOST: test
          DB_PORT: 5432
          DEBUG_MODE: True
      run: |
        python manage.py test
    - name: Run server
      env:
        SECRET_KEY: secretkey
        DB_NAME: test
        DB_USER: test
        DB_PASSWORD: test
        DB_HOST: test
        DB_PORT: 5432
        DEBUG_MODE: True
      run: |
        python manage.py runserver
